import "./globals.css";
import { Inter } from "next/font/google";
import { CampaignProvider } from "@/context/campaign";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Marvel Legendary Campaign Timeline",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CampaignProvider>{children}</CampaignProvider>
      </body>
    </html>
  );
}
